module.exports = [
  {
    name: "Fullbody HIIT",
    link: "https://www.youtube.com/AO-qmqostHE",
    type: "HIIT",
    duration: "45 minutes",
    equipment: "dumbells, waterbottles, or related",
  },
  {
    name: "Leg Pain Relief",
    link: "hhttps://www.youtube.com/8YXglW9kvH4",
    type: "Stretch and Relief",
    duration: "20 minutes",
    equipment: "your body",
  },
  {
    name: "Lower Back Relief",
    link: "https://www.youtube.com/p6CMso14NWk",
    type: "Stretch and Relief",
    duration: "20 minutes",
    equipment: "your body",
  },
  {
    name: "Lower Back and HIP Relief",
    link: "https://www.youtube.com/_lT5Cd4cDTc",
    type: "Stretch and Relief",
    duration: "35 minutes",
    equipment: "your body",
  },
  {
    name: "Fullbody HIIT",
    link: "https://www.youtube.com/wwkrup_TG6I",
    type: "HIIT",
    duration: "20 minutes",
    equipment: "your body",
  },
  {
    name: "Fullbody Weight Training",
    link: "https://www.youtube.com/jDF4XiUtXGM",
    type: "Weight Training",
    duration: "35 minutes",
    equipment: "dumbells, waterbottles, or related",
  },
  {
    name: "1hr Fullbody Weight Training",
    link: "https://www.youtube.com/AO-qmqostHE",
    type: "Weight Training",
    duration: "60 minutes",
    equipment: "dumbells, waterbottles, or related",
  },
  {
    name: "Arm Weight Training",
    link: "https://www.youtube.com/km4h2_IXBZY",
    type: "Weight Training",
    duration: "20 minutes",
    equipment: "dumbells, waterbottles, or related",
  },
  {
    name: "Intense Ab Workout",
    link: "https://www.youtube.com/rJV9xByEPho",
    type: "Core Training",
    duration: "20 minutes",
    equipment: "your body",
  },
  {
    name: "Leg Workout",
    link: "https://www.youtube.com/3ru8I7LU3Dc",
    type: "Weight Training",
    duration: "20 minutes",
    equipment: "dumbells, waterbottles, or your body",
  },
  {
    name: "Butt and Leg Weight Training",
    link: "https://www.youtube.com/5pMF6ei4AT8",
    type: "Weight Training",
    duration: "45 minutes",
    equipment: "dumbells, waterbottles, or your body",
  },
  {
    name: "Shoulder Weight Training",
    link: "https://www.youtube.com/2keb031pDGk",
    type: "Weight Training",
    duration: "20 minutes",
    equipment: "dumbells, waterbottles, or your body",
  },
  {
    name: "MMA Workout",
    link: "https://www.youtube.com/WIaZUWEuV-g",
    type: "MMA Training",
    duration: "40 minutes",
    equipment: "dumbells, waterbottles, or your body",
  },
  {
    name: "Chest and Tricep Workout",
    link: "https://www.youtube.com/PInAyHosJEQ",
    type: "Weight Training",
    duration: "40 minutes",
    equipment: "dumbells, waterbottles, or your body",
  },
  {
    name: "Chest and Tricep Workout",
    link: "https://www.youtube.com/vCIHZ-UVYsU",
    type: "Weight Training",
    duration: "25 minutes",
    equipment: "dumbells, waterbottles, or your body",
  },
  {
    name: "Arm and Shoulder Workout",
    link: "https://www.youtube.com/kEg9a8JoxOY",
    type: "Weight Training",
    duration: "40 minutes",
    equipment: "dumbells, waterbottles, or your body",
  },
  {
    name: "Arm and Shoulder Relief",
    link: "https://www.youtube.com/6vfamrwD7ks",
    type: "Stretch and Relief",
    duration: "20 minutes",
    equipment: "your body",
  },
  {
    name: "Back Weight Training",
    link: "https://www.youtube.com/LkkvW9ZbAv4",
    type: "Weight Training",
    duration: "25 minutes",
    equipment: "dumbells, barbell, waterbottles, or your body"
  }
]
